name: Build & deploy Python Azure Function

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Get your code
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Log in to Azure using the SP
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3. Set up Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 4. Install dependencies
      - name: Install requirements
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      # 5. Zip up your function
      - name: Pack function
        run: zip -r function.zip . -x ".git/*" -x ".venv/*"

      # 6. Deploy via Azure CLI
      - name: Deploy to Azure Function
        run: |
          az functionapp deployment source config-zip \
            --resource-group tfc-intake-functions \
            --name tfc-intake-sanitize \
            --src function.zip
